language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

script:
  - mvn clean package --settings settings.xml

deploy:
  provider: script
  script: mvn clean deploy  -DskipTests  --settings settings.xml
  on:
    branch: master
