server:
  port: 8701

#MongoDB
spring:
  data:
    mongodb:
      database: nbm_cash_net
      host: 52.184.36.152
      port: 27017
      username: admin
      password: haohao123
  redis:
    port: 36888
    password: haohao123
    database: 8
    host: 52.184.36.152
    jedis:
      pool:
        min-idle: 5
        max-idle: 15
        max-wait: 30000
        max-active: 60
    timeout: 60

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG

log:
  system:
    name: seamless
  machine:
    num: 01